import { requireLegacyId } from "./helpers.ts";
import {
  base,
  booleanValue,
  dateValue,
  list,
  numberValue,
  relation,
  type SourceMapping,
  text,
} from "./mappings.ts";

const named = (
  sourceType: string,
  table: string,
  sourceField: string,
  targetField = "name",
): SourceMapping => ({
  phase: "remaining",
  sourceType,
  table,
  map: (r) => ({
    ...base(r),
    [targetField]: text(r[sourceField]) || requireLegacyId(r),
  }),
});

const range = (value: unknown, index: number) =>
  Array.isArray(value) && typeof value[index] === "string"
    ? value[index]
    : null;

export const remainingMappings: SourceMapping[] = [
  named("bento_mainingredients", "bento_main_ingredients", "main ingredient"),
  named("bento_maintype", "bento_main_types", "main type"),
  named("bento_numberofcolumn", "bento_column_types", "no of column / type"),
  named("bento_specialrequest", "bento_special_requests", "special request"),
  named(
    "ds_bento_additionalitem",
    "bento_additional_items",
    "item",
    "description",
  ),
  named("ds_bento_eventpart", "bento_event_parts", "item", "description"),
  {
    phase: "remaining",
    sourceType: "ds_collection",
    table: "product_collections",
    map: (r) => ({
      ...base(r),
      channel_id: null,
      channel_legacy_id: text(r.Channel),
      name: text(r["Display Name"]) || requireLegacyId(r),
      sort_order: numberValue(r.Rank),
    }),
    relations: [relation("channel_legacy_id", "channel_id", "channels")],
  },
  {
    phase: "remaining",
    sourceType: "ds_cooktype",
    table: "cook_types",
    map: (r) => ({
      ...base(r),
      name: text(r.Type) || requireLegacyId(r),
      workload_score: numberValue(r.WorkloadScore),
    }),
  },
  {
    phase: "remaining",
    sourceType: "ds_cost_type",
    table: "cost_types",
    map: (r) => ({
      ...base(r),
      name: text(r.cost_type) || requireLegacyId(r),
      is_active: booleanValue(r.Active, true),
      is_advertising: booleanValue(r.ads),
      is_brand: booleanValue(r.brand),
    }),
  },
  {
    phase: "remaining",
    sourceType: "ds_customer_tag_type",
    table: "customer_tag_types",
    map: (r) => ({
      ...base(r),
      name: text(r["customer tag type"]) || requireLegacyId(r),
      is_active: booleanValue(r.Active, true),
    }),
  },
  {
    phase: "remaining",
    sourceType: "ds_customer_tag",
    table: "customer_tags",
    map: (r) => ({
      ...base(r),
      customer_tag_type_id: null,
      customer_tag_type_legacy_id: text(r.DS_customer_tag_type),
      name: text(r.tag) || requireLegacyId(r),
      is_active: booleanValue(r.Active, true),
    }),
    relations: [
      relation(
        "customer_tag_type_legacy_id",
        "customer_tag_type_id",
        "customer_tag_types",
      ),
    ],
  },
  {
    phase: "remaining",
    sourceType: "ds_deliverysurcharge",
    table: "delivery_surcharge_types",
    map: (r) => ({
      ...base(r),
      name: text(r.charge_name) || requireLegacyId(r),
      is_active: booleanValue(r.active, true),
    }),
  },
  {
    phase: "remaining",
    sourceType: "ds_festival",
    table: "festivals",
    map: (r) => ({
      ...base(r),
      name: text(r.Festival) || requireLegacyId(r),
      is_active: booleanValue(r.Active, true),
    }),
  },
  {
    phase: "remaining",
    sourceType: "ds_purchasetype",
    table: "purchase_types",
    map: (r) => ({
      ...base(r),
      name: text(r.Type) || requireLegacyId(r),
      is_active: booleanValue(r.Active, true),
    }),
  },
  {
    phase: "remaining",
    sourceType: "ds_quote_delivery",
    table: "quote_delivery_templates",
    map: (r) => ({
      ...base(r),
      content: text(r.display),
      is_editable: booleanValue(r.editable),
    }),
  },
  {
    phase: "remaining",
    sourceType: "ds_quote_payment",
    table: "quote_payment_templates",
    map: (r) => ({
      ...base(r),
      content: text(r.display),
      is_editable: booleanValue(r.editable),
    }),
  },
  {
    phase: "remaining",
    sourceType: "ds_quote_t&c",
    table: "quote_terms_templates",
    map: (r) => ({
      ...base(r),
      content: text(r.display),
      is_editable: booleanValue(r.editable),
    }),
  },
  {
    phase: "remaining",
    sourceType: "ds_salespartner",
    table: "sales_partners",
    map: (r) => ({
      ...base(r),
      name: text(r.Name) || requireLegacyId(r),
      phone: text(r["Phone no."]),
      is_active: booleanValue(r.active, true),
    }),
  },
  {
    phase: "remaining",
    sourceType: "ds_super_motorcade_subdriver",
    table: "delivery_team_drivers",
    map: (r) => ({
      ...base(r),
      delivery_team_id: null,
      delivery_team_legacy_id: text(r.DS_Super_Motorcade),
      display_name: text(r["Display Name"]) || requireLegacyId(r),
      is_active: booleanValue(r.Active, true),
    }),
    relations: [
      relation(
        "delivery_team_legacy_id",
        "delivery_team_id",
        "delivery_teams",
      ),
    ],
  },
  named("ds_tags", "product_tags", "Display Name"),
  {
    phase: "remaining",
    sourceType: "ds_type",
    table: "product_types",
    map: (r) => ({
      ...base(r),
      channel_id: null,
      channel_legacy_id: text(r.channel) || text(r.Channel),
      name: text(r["Display Name"]) || requireLegacyId(r),
      sort_order: numberValue(r.Rank),
    }),
    relations: [relation("channel_legacy_id", "channel_id", "channels")],
  },
  {
    phase: "remaining",
    sourceType: "dsao_blockdate",
    table: "order_block_dates",
    map: (r) => ({ ...base(r), blocked_at: dateValue(r.blockDate) }),
  },
  {
    phase: "remaining",
    sourceType: "dsaoproduct",
    table: "channel_products",
    map: (r) => ({
      ...base(r),
      channel_id: null,
      channel_legacy_id: text(r.Channels),
      product_id: null,
      product_legacy_id: text(r.Product),
    }),
    relations: [
      relation("channel_legacy_id", "channel_id", "channels"),
      relation("product_legacy_id", "product_id", "products"),
    ],
  },
  {
    phase: "remaining",
    sourceType: "dscommuchannels(quote)",
    table: "quote_communication_channels",
    map: (r) => ({
      ...base(r),
      name: text(r.Channels) || requireLegacyId(r),
      is_active: booleanValue(r.Active, true),
    }),
  },
  {
    phase: "remaining",
    sourceType: "dsreminderperson(first)",
    table: "quote_first_reminder_contacts",
    map: (r) => ({
      ...base(r),
      name: text(r.name) || requireLegacyId(r),
      phone: text(r["phone no."]),
      reminder_hours: numberValue(r.hrs),
    }),
  },
  {
    phase: "remaining",
    sourceType: "dsreminderperson(second)",
    table: "quote_second_reminder_contacts",
    map: (r) => ({
      ...base(r),
      name: text(r.name) || requireLegacyId(r),
      phone: text(r["phone.no"]),
      reminder_hours: numberValue(r.hrs),
    }),
  },
  {
    phase: "remaining",
    sourceType: "dssourceofsales(quote)",
    table: "quote_sales_sources",
    map: (r) => ({
      ...base(r),
      name: text(r.Source) || requireLegacyId(r),
      is_active: booleanValue(r.Active, true),
    }),
  },
  named("osdriver_menu", "osdriver_menus", "Display Name"),
  {
    phase: "remaining",
    sourceType: "a_label",
    table: "product_labels",
    map: (r) => ({
      ...base(r),
      product_id: null,
      product_legacy_id: text(r.Product),
      packing_material_id: null,
      packing_material_legacy_id: text(r.Packing),
      display_name: text(r["Display Name A"]),
      quantity_label: text(r["Display Name B"]),
    }),
    relations: [
      relation("product_legacy_id", "product_id", "products"),
      relation(
        "packing_material_legacy_id",
        "packing_material_id",
        "packing_materials",
      ),
    ],
  },
  {
    phase: "remaining",
    sourceType: "print_label",
    table: "print_labels",
    map: (r) => ({
      ...base(r),
      order_id: null,
      order_legacy_id: text(r.A_order),
      display_name: text(r["Display Name"]),
    }),
    relations: [relation("order_legacy_id", "order_id", "orders")],
  },
  {
    phase: "remaining",
    sourceType: "b_adscostweekly",
    table: "advertising_costs",
    map: (r) => ({
      ...base(r),
      cost_type_id: null,
      cost_type_legacy_id: text(r.Ads_type),
      channel_id: null,
      channel_legacy_id: text(r.Channel),
      amount: numberValue(r["ads cost amount"]),
      range_start: dateValue(r.RangeStart) ||
        dateValue(range(r["Date_range(mon to sun)"], 0)),
      range_end: dateValue(range(r["Date_range(mon to sun)"], 1)),
      sorting_key: numberValue(r.dateText_forSorting),
      remarks: text(r.Remark),
    }),
    relations: [
      relation("cost_type_legacy_id", "cost_type_id", "cost_types"),
      relation("channel_legacy_id", "channel_id", "channels"),
    ],
  },
  {
    phase: "remaining",
    sourceType: "b_costmonthly",
    table: "monthly_costs",
    map: (r) => ({
      ...base(r),
      cost_type_id: null,
      cost_type_legacy_id: text(r.cost_type),
      primary_channel_id: null,
      primary_channel_legacy_id: text(r["Ads_single Brand"]),
      festival_id: null,
      festival_legacy_id: text(r.Festival),
      month_at: dateValue(r.Month),
      non_peak_amount: numberValue(r["Non-Peak Amount"]),
      festival_amount: numberValue(r["Festival amount"]),
      festival_range_start: dateValue(range(r["Festival Range"], 0)),
      festival_range_end: dateValue(range(r["Festival Range"], 1)),
      season: text(r["OS season"]),
      remarks: text(r.Remark),
    }),
    relations: [
      relation("cost_type_legacy_id", "cost_type_id", "cost_types"),
      relation(
        "primary_channel_legacy_id",
        "primary_channel_id",
        "channels",
      ),
      relation("festival_legacy_id", "festival_id", "festivals"),
    ],
    children: (records, parentIds) => [{
      table: "monthly_cost_channels",
      onConflict: "monthly_cost_id,channel_legacy_id",
      relations: [
        relation("channel_legacy_id", "channel_id", "channels"),
      ],
      rows: records.flatMap((r) =>
        list(r.Channels).map((channelLegacyId) => ({
          monthly_cost_id: parentIds.get(requireLegacyId(r)),
          monthly_cost_legacy_id: requireLegacyId(r),
          channel_id: null,
          channel_legacy_id: channelLegacyId,
        }))
      ),
    }],
  },
  {
    phase: "remaining",
    sourceType: "b_supplierpurchase",
    table: "supplier_purchases",
    map: (r) => ({
      ...base(r),
      supplier_id: null,
      supplier_legacy_id: text(r.Supplier),
      purchase_type_id: null,
      purchase_type_legacy_id: text(r.DS_purchase_type),
      purchased_at: dateValue(r.Date),
      amount: numberValue(r.Amount),
    }),
    relations: [
      relation("supplier_legacy_id", "supplier_id", "suppliers"),
      relation(
        "purchase_type_legacy_id",
        "purchase_type_id",
        "purchase_types",
      ),
    ],
  },
  {
    phase: "remaining",
    sourceType: "b_deliveryschedule_surcharge",
    table: "delivery_surcharges",
    map: (r) => ({
      ...base(r),
      delivery_id: null,
      delivery_legacy_id: text(r.B_delivery_schedule),
      surcharge_type_id: null,
      surcharge_type_legacy_id: text(r["DS_delivery surchage"]),
      amount: numberValue(r.Amount),
    }),
    relations: [
      relation("delivery_legacy_id", "delivery_id", "deliveries"),
      relation(
        "surcharge_type_legacy_id",
        "surcharge_type_id",
        "delivery_surcharge_types",
      ),
    ],
  },
  {
    phase: "remaining",
    sourceType: "s_paymentreport",
    table: "payment_settlements",
    map: (r) => ({
      ...base(r),
      channel_id: null,
      channel_legacy_id: text(r.Channels),
      payment_method_id: null,
      payment_method_legacy_id: text(r["Payment Method"]),
      invoice_number: text(r["Invoice no."]),
      payout_at: dateValue(r["Payout date"]),
      receipt_number: text(r["Rec no."]),
      gross_amount: numberValue(r["total amount"]),
      charges: numberValue(r.Charges),
      net_amount: numberValue(r["Net Amount"]),
    }),
    relations: [
      relation("channel_legacy_id", "channel_id", "channels"),
      relation(
        "payment_method_legacy_id",
        "payment_method_id",
        "payment_methods",
      ),
    ],
    children: (records, parentIds) => [{
      table: "payment_settlement_payments",
      onConflict: "payment_settlement_id,payment_legacy_id",
      relations: [relation("payment_legacy_id", "payment_id", "payments")],
      rows: records.flatMap((r) =>
        list(r.S_payment).map((paymentLegacyId) => ({
          payment_settlement_id: parentIds.get(requireLegacyId(r)),
          payment_settlement_legacy_id: requireLegacyId(r),
          payment_id: null,
          payment_legacy_id: paymentLegacyId,
        }))
      ),
    }],
  },
  {
    phase: "remaining",
    sourceType: "s_packages_choiceset",
    table: "package_choice_sets",
    map: (r) => ({
      ...base(r),
      package_id: null,
      package_legacy_id: text(r.Package),
      choice_type: text(r.RealType),
      maximum_choices: numberValue(r["Max Number"]),
    }),
    relations: [relation("package_legacy_id", "package_id", "packages")],
  },
  {
    phase: "remaining",
    sourceType: "cal_control",
    table: "production_calculations",
    map: (r) => ({
      ...base(r),
      order_id: null,
      order_legacy_id: text(r.order),
      package_id: null,
      package_legacy_id: text(r.Package),
      package_choice_set_id: null,
      package_choice_set_legacy_id: text(r.Package_Set),
    }),
    relations: [
      relation("order_legacy_id", "order_id", "orders"),
      relation("package_legacy_id", "package_id", "packages"),
      relation(
        "package_choice_set_legacy_id",
        "package_choice_set_id",
        "package_choice_sets",
      ),
    ],
  },
  {
    phase: "remaining",
    sourceType: "cal_package_choice",
    table: "order_package_choice_snapshots",
    map: (r) => ({
      ...base(r),
      production_calculation_id: null,
      production_calculation_legacy_id: text(r.Control),
      order_id: null,
      order_legacy_id: text(r.Order),
      package_id: null,
      package_legacy_id: text(r.Package),
      package_product_id: null,
      package_product_legacy_id: text(r.Package_Product),
      package_choice_set_id: null,
      package_choice_set_legacy_id: text(r.S_Package_Choice),
      product_type_id: null,
      product_type_legacy_id: text(r.Type),
      maximum_choices: numberValue(r.MaxNum),
      is_selected: booleanValue(r.Selected),
    }),
    relations: [
      relation(
        "production_calculation_legacy_id",
        "production_calculation_id",
        "production_calculations",
      ),
      relation("order_legacy_id", "order_id", "orders"),
      relation("package_legacy_id", "package_id", "packages"),
      relation(
        "package_product_legacy_id",
        "package_product_id",
        "package_products",
      ),
      relation(
        "package_choice_set_legacy_id",
        "package_choice_set_id",
        "package_choice_sets",
      ),
      relation("product_type_legacy_id", "product_type_id", "product_types"),
    ],
  },
  {
    phase: "remaining",
    sourceType: "quote_bento_additionalitem",
    table: "order_bento_additional_items",
    map: (r) => ({
      ...base(r),
      order_id: null,
      order_legacy_id: text(r.A_order),
      additional_item_id: null,
      additional_item_legacy_id: text(r["DS_addiction item ID"]),
      description_snapshot: text(r["additional item"]),
      sort_order: numberValue(r.sort),
    }),
    relations: [
      relation("order_legacy_id", "order_id", "orders"),
      relation(
        "additional_item_legacy_id",
        "additional_item_id",
        "bento_additional_items",
      ),
    ],
  },
  {
    phase: "remaining",
    sourceType: "quote_bento_eventpart",
    table: "order_bento_event_parts",
    map: (r) => ({
      ...base(r),
      order_id: null,
      order_legacy_id: text(r.A_order),
      event_part_id: null,
      event_part_legacy_id: text(r["ds_bento_event item"]),
      description_snapshot: text(r["quote_event item"]),
      price_snapshot: numberValue(r["quote item_price"]),
      sort_order: numberValue(r.sort),
    }),
    relations: [
      relation("order_legacy_id", "order_id", "orders"),
      relation(
        "event_part_legacy_id",
        "event_part_id",
        "bento_event_parts",
      ),
    ],
  },
  {
    phase: "remaining",
    sourceType: "quote_paymentmethod",
    table: "order_payment_method_snapshots",
    map: (r) => ({
      ...base(r),
      order_id: null,
      order_legacy_id: text(r.A_order),
      content: text(r.method),
    }),
    relations: [relation("order_legacy_id", "order_id", "orders")],
  },
  {
    phase: "remaining",
    sourceType: "quote_t&c",
    table: "order_terms_snapshots",
    map: (r) => ({
      ...base(r),
      order_id: null,
      order_legacy_id: text(r.A_order),
      content: text(r["T&C"]),
    }),
    relations: [relation("order_legacy_id", "order_id", "orders")],
  },
  {
    phase: "remaining",
    sourceType: "s_comment",
    table: "order_timeline_entries",
    map: (r) => ({
      ...base(r),
      order_id: null,
      order_legacy_id: text(r.A_order),
      category: text(r.category),
      comment: text(r.comment),
      customer_email_snapshot: text(r["customer email"]),
    }),
    relations: [relation("order_legacy_id", "order_id", "orders")],
  },
  {
    phase: "remaining",
    sourceType: "s_customer_tag",
    table: "customer_tag_assignments",
    map: (r) => ({
      ...base(r),
      customer_email_snapshot: text(r.Email),
      customer_tag_id: null,
      customer_tag_legacy_id: text(r.tag),
      customer_tag_type_id: null,
      customer_tag_type_legacy_id: text(r["tag type"]),
    }),
    relations: [
      relation(
        "customer_tag_legacy_id",
        "customer_tag_id",
        "customer_tags",
      ),
      relation(
        "customer_tag_type_legacy_id",
        "customer_tag_type_id",
        "customer_tag_types",
      ),
    ],
  },
];
