import { useEffect, useState, type FormEvent } from "react";
import { useTranslation } from "react-i18next";
import { Pencil, Plus, Trash2 } from "lucide-react";
import { useCurrentPageAccess } from "@/auth/use-page-access";
import { Button } from "@/components/ui/button";
import { ListTable } from "@/components/ui/list-table";
import { SidePanel } from "@/components/ui/side-panel";
import { Switch } from "@/components/ui/switch";
import { supabase } from "@/lib/supabase";

const pnlCategories = ["Discount", "其他營運開支", "員工成本", "外賣平台", "推廣費用", "收款平台手續費", "水電費", "租金", "行政費用"];
type PnlCost = { id: string; sortOrder: number; category: string; name: string; isActive: boolean };

export function MonthlyPnlCostCategoriesPage() {
  const { t } = useTranslation(); const access = useCurrentPageAccess(); const canEdit = access.canAccess("restaurant.settings.monthly_pnl_cost_categories.edit"); const canDelete = access.canAccess("restaurant.settings.monthly_pnl_cost_categories.delete");
  const [rows, setRows] = useState<PnlCost[]>([]); const [loading, setLoading] = useState(true); const [open, setOpen] = useState(false); const [editing, setEditing] = useState<PnlCost | null>(null); const [category, setCategory] = useState(""); const [name, setName] = useState(""); const [saving, setSaving] = useState(false);
  const load = () => { setLoading(true); void supabase.from("restaurant_monthly_pnl_cost_categories").select("id,sort_order,category,name,is_active").is("archived_at", null).order("sort_order").order("name").then(({ data }) => { setRows((data ?? []).map((row) => ({ id: row.id as string, sortOrder: Number(row.sort_order ?? 0), category: row.category as string, name: row.name as string, isActive: Boolean(row.is_active) }))); setLoading(false); }, () => setLoading(false)); };
  useEffect(load, []);
  const close = () => { setOpen(false); setEditing(null); setCategory(""); setName(""); };
  const edit = (row: PnlCost | null) => { setEditing(row); setCategory(row?.category ?? ""); setName(row?.name ?? ""); setOpen(true); };
  const submit = async (event: FormEvent) => { event.preventDefault(); if (!category || !name.trim()) return; setSaving(true); const fields = { category, name: name.trim() }; if (editing) await supabase.from("restaurant_monthly_pnl_cost_categories").update(fields).eq("id", editing.id); else await supabase.from("restaurant_monthly_pnl_cost_categories").insert({ legacy_id: `web-monthly-pnl-cost-${crypto.randomUUID()}`, sort_order: (rows.at(-1)?.sortOrder ?? 0) + 1, is_active: true, ...fields }); close(); load(); setSaving(false); };
  const toggle = async (row: PnlCost) => { await supabase.from("restaurant_monthly_pnl_cost_categories").update({ is_active: !row.isActive }).eq("id", row.id); load(); };
  const remove = async (row: PnlCost) => { if (!window.confirm(t("monthlyPnlCostCategories.deleteConfirm", { name: row.name }))) return; await supabase.from("restaurant_monthly_pnl_cost_categories").update({ archived_at: new Date().toISOString() }).eq("id", row.id); load(); };
  return <section className="ingredients-page"><header className="page-heading ingredients-heading"><div><span className="eyebrow">{t("navigation.restaurant")}</span><h1>{t("monthlyPnlCostCategories.title")}</h1><p>{t("monthlyPnlCostCategories.description")}</p></div>{canEdit ? <Button onClick={() => edit(null)}><Plus />{t("monthlyPnlCostCategories.add")}</Button> : null}</header><article className="panel ingredients-panel"><ListTable className="ingredients-table-wrap" loading={loading} loadingLabel={t("monthlyPnlCostCategories.loading")} skeletonColumns={canEdit || canDelete ? 5 : 4} header={<tr><th>{t("monthlyPnlCostCategories.columns.order")}</th><th>{t("monthlyPnlCostCategories.columns.category")}</th><th>{t("monthlyPnlCostCategories.columns.name")}</th><th>{t("monthlyPnlCostCategories.columns.status")}</th>{canEdit || canDelete ? <th aria-label={t("monthlyPnlCostCategories.columns.actions")} /> : null}</tr>}>{rows.map((row) => <tr key={row.id}><td>{row.sortOrder}</td><td>{row.category}</td><td><strong>{row.name}</strong></td><td>{canEdit ? <Switch checked={row.isActive} onCheckedChange={() => void toggle(row)} aria-label={row.isActive ? t("monthlyPnlCostCategories.active") : t("monthlyPnlCostCategories.inactive")} /> : row.isActive ? t("monthlyPnlCostCategories.active") : t("monthlyPnlCostCategories.inactive")}</td>{canEdit || canDelete ? <td className="table-actions-cell"><div className="table-row-actions">{canEdit ? <Button size="icon" variant="outline" aria-label={t("monthlyPnlCostCategories.edit")} onClick={() => edit(row)}><Pencil /></Button> : null}{canDelete ? <Button size="icon" variant="destructive" aria-label={t("monthlyPnlCostCategories.delete")} onClick={() => void remove(row)}><Trash2 /></Button> : null}</div></td> : null}</tr>)}</ListTable></article><SidePanel open={open} title={t(editing ? "monthlyPnlCostCategories.editTitle" : "monthlyPnlCostCategories.addTitle")} onClose={close} closeLabel={t("monthlyPnlCostCategories.close")} footer={<><Button variant="outline" onClick={close}>{t("monthlyPnlCostCategories.cancel")}</Button><Button type="submit" form="monthly-pnl-cost-category-form" disabled={saving}>{saving ? t("monthlyPnlCostCategories.saving") : t("monthlyPnlCostCategories.save")}</Button></>}><form id="monthly-pnl-cost-category-form" className="ingredients-form" onSubmit={(event) => void submit(event)}><label className="ingredients-field"><span>{t("monthlyPnlCostCategories.fields.category")}</span><select value={category} onChange={(event) => setCategory(event.target.value)}><option value="">{t("monthlyPnlCostCategories.fields.categoryPlaceholder")}</option>{pnlCategories.map((value) => <option key={value} value={value}>{value}</option>)}</select></label><label className="ingredients-field"><span>{t("monthlyPnlCostCategories.fields.name")}</span><input value={name} onChange={(event) => setName(event.target.value)} placeholder={t("monthlyPnlCostCategories.fields.namePlaceholder")} /></label></form></SidePanel></section>;
}
