import { useEffect, useState, type FormEvent } from "react";
import { useTranslation } from "react-i18next";
import { Pencil, Plus, Trash2 } from "lucide-react";
import { useCurrentPageAccess } from "@/auth/use-page-access";
import { Button } from "@/components/ui/button";
import { ListTable } from "@/components/ui/list-table";
import { SidePanel } from "@/components/ui/side-panel";
import { Switch } from "@/components/ui/switch";
import { supabase } from "@/lib/supabase";

type Holiday = { id: string; sortOrder: number; name: string; isActive: boolean };

export function RestaurantHolidaysPage() {
  const { t } = useTranslation(); const access = useCurrentPageAccess(); const canEdit = access.canAccess("restaurant.settings.holidays.edit"); const canDelete = access.canAccess("restaurant.settings.holidays.delete");
  const [rows, setRows] = useState<Holiday[]>([]); const [loading, setLoading] = useState(true); const [open, setOpen] = useState(false); const [editing, setEditing] = useState<Holiday | null>(null); const [sortOrder, setSortOrder] = useState(""); const [name, setName] = useState(""); const [active, setActive] = useState(true); const [saving, setSaving] = useState(false);
  const load = () => { setLoading(true); void supabase.from("restaurant_holidays").select("id,sort_order,name,is_active").is("archived_at", null).order("sort_order").order("name").then(({ data }) => { setRows((data ?? []).map((row) => ({ id: row.id as string, sortOrder: Number(row.sort_order ?? 0), name: row.name as string, isActive: Boolean(row.is_active) }))); setLoading(false); }, () => setLoading(false)); };
  useEffect(load, []);
  const close = () => { setOpen(false); setEditing(null); setSortOrder(""); setName(""); setActive(true); };
  const edit = (row: Holiday | null) => { setEditing(row); setSortOrder(row?.sortOrder.toString() ?? ((rows.at(-1)?.sortOrder ?? 0) + 1).toString()); setName(row?.name ?? ""); setActive(row?.isActive ?? true); setOpen(true); };
  const submit = async (event: FormEvent) => { event.preventDefault(); if (!name.trim()) return; setSaving(true); const now = new Date().toISOString(); const fields = { sort_order: Number(sortOrder) || 0, name: name.trim(), is_active: active, updated_at: now, bubble_modified_at: now }; if (editing) await supabase.from("restaurant_holidays").update(fields).eq("id", editing.id); else await supabase.from("restaurant_holidays").insert({ legacy_id: `web-restaurant-holiday-${crypto.randomUUID()}`, bubble_created_at: now, ...fields }); close(); load(); setSaving(false); };
  const toggle = async (row: Holiday) => { await supabase.from("restaurant_holidays").update({ is_active: !row.isActive, updated_at: new Date().toISOString() }).eq("id", row.id); load(); };
  const remove = async (row: Holiday) => { if (!window.confirm(t("restaurantHolidays.deleteConfirm", { name: row.name }))) return; await supabase.from("restaurant_holidays").update({ archived_at: new Date().toISOString(), updated_at: new Date().toISOString() }).eq("id", row.id); load(); };
  return <section className="ingredients-page"><header className="page-heading ingredients-heading"><div><span className="eyebrow">{t("navigation.restaurant")}</span><h1>{t("restaurantHolidays.title")}</h1><p>{t("restaurantHolidays.description")}</p></div>{canEdit ? <Button onClick={() => edit(null)}><Plus />{t("restaurantHolidays.add")}</Button> : null}</header><article className="panel ingredients-panel"><ListTable className="ingredients-table-wrap" loading={loading} loadingLabel={t("restaurantHolidays.loading")} skeletonColumns={canEdit || canDelete ? 4 : 3} header={<tr><th>{t("restaurantHolidays.columns.order")}</th><th>{t("restaurantHolidays.columns.name")}</th><th>{t("restaurantHolidays.columns.status")}</th>{canEdit || canDelete ? <th aria-label={t("restaurantHolidays.columns.actions")} /> : null}</tr>}>{rows.map((row) => <tr key={row.id}><td>{row.sortOrder}</td><td><strong>{row.name}</strong></td><td>{canEdit ? <Switch checked={row.isActive} onCheckedChange={async (value) => { await supabase.from("restaurant_holidays").update({ is_active: value, updated_at: new Date().toISOString() }).eq("id", row.id); load(); }} /> : row.isActive ? t("restaurantHolidays.active") : t("restaurantHolidays.inactive")}</td>{canEdit || canDelete ? <td className="table-actions-cell"><div className="table-row-actions">{canEdit ? <Button size="icon" variant="outline" aria-label={t("restaurantHolidays.edit")} onClick={() => edit(row)}><Pencil /></Button> : null}{canDelete ? <Button size="icon" variant="destructive" aria-label={t("restaurantHolidays.delete")} onClick={() => void remove(row)}><Trash2 /></Button> : null}</div></td> : null}</tr>)}</ListTable></article><SidePanel open={open} title={t(editing ? "restaurantHolidays.editTitle" : "restaurantHolidays.addTitle")} onClose={close} closeLabel={t("restaurantHolidays.close")} footer={<><Button variant="outline" onClick={close}>{t("restaurantHolidays.cancel")}</Button><Button type="submit" form="restaurant-holiday-form" disabled={saving}>{saving ? t("restaurantHolidays.saving") : t("restaurantHolidays.save")}</Button></>}><form id="restaurant-holiday-form" className="ingredients-form" onSubmit={(event) => void submit(event)}><label className="ingredients-field"><span>{t("restaurantHolidays.fields.order")}</span><input type="number" min="0" value={sortOrder} onChange={(event) => setSortOrder(event.target.value)} /></label><label className="ingredients-field"><span>{t("restaurantHolidays.fields.name")}</span><input value={name} onChange={(event) => setName(event.target.value)} placeholder={t("restaurantHolidays.fields.namePlaceholder")} /></label><label className="ingredients-field"><span>{t("restaurantHolidays.fields.status")}</span><Switch checked={active} onCheckedChange={setActive} /></label></form></SidePanel></section>;
}
