alter table public.orders
  add column if not exists delivery_district_id uuid
    references public.delivery_districts (id);

create index if not exists orders_delivery_district_id_idx
  on public.orders (delivery_district_id);

comment on column public.orders.delivery_district_id is
  'Planned district retained on the order before a delivery is generated by the factory-send workflow.';

update public.orders as orders
set delivery_district_id = coalesce(
  orders.delivery_district_id,
  (
    select delivery.district_id
    from public.deliveries as delivery
    where delivery.order_id = orders.id
    order by delivery.created_at, delivery.id
    limit 1
  )
)
where orders.delivery_district_id is null
  and exists (
    select 1
    from public.deliveries as delivery
    where delivery.order_id = orders.id
      and delivery.district_id is not null
  );

create or replace function private.defer_order_delivery_until_factory_send()
returns trigger
language plpgsql
security definer
set search_path = public, private, pg_temp
as $$
declare
  v_document_type text;
  v_is_sent_to_factory boolean;
begin
  select orders.document_type, orders.is_sent_to_factory
  into v_document_type, v_is_sent_to_factory
  from public.orders
  where orders.id = new.order_id;

  if not found then
    raise exception 'delivery_order_not_found' using errcode = 'P0002';
  end if;

  if v_document_type = 'order' and v_is_sent_to_factory is distinct from true then
    -- Older clients and quote conversion may still attempt an early insert.
    -- Preserve their planned fields on the order, but do not create a delivery.
    update public.orders
    set delivery_district_id = coalesce(new.district_id, delivery_district_id),
        shipping_method_id = coalesce(new.shipping_method_id, shipping_method_id),
        delivery_at = coalesce(new.delivery_at, delivery_at),
        delivery_time = coalesce(new.delivery_time, delivery_time),
        ship_out_time = coalesce(new.ship_out_time, ship_out_time),
        updated_at = now()
    where id = new.order_id;
    return null;
  end if;

  return new;
end;
$$;

drop trigger if exists defer_order_delivery_until_factory_send
  on public.deliveries;
create trigger defer_order_delivery_until_factory_send
before insert on public.deliveries
for each row execute function private.defer_order_delivery_until_factory_send();

create or replace function public.set_order_factory_status(
  p_order_id uuid,
  p_sent boolean
)
returns uuid
language plpgsql
security invoker
set search_path = public, pg_temp
as $$
declare
  v_order public.orders%rowtype;
  v_delivery_id uuid;
begin
  select * into v_order
  from public.orders
  where id = p_order_id
  for update;

  if not found
    or v_order.document_type is distinct from 'order'
    or v_order.archived_at is not null
  then
    raise exception 'order_not_found' using errcode = 'P0002';
  end if;

  if p_sent and coalesce(v_order.do_not_send_to_factory, false) then
    raise exception 'order_factory_send_disabled' using errcode = '22023';
  end if;

  if p_sent and v_order.delivery_district_id is null then
    raise exception 'order_delivery_district_required' using errcode = '22023';
  end if;

  update public.orders
  set is_sent_to_factory = p_sent,
      updated_at = now()
  where id = p_order_id;

  select delivery.id into v_delivery_id
  from public.deliveries as delivery
  where delivery.order_id = p_order_id
  order by delivery.created_at, delivery.id
  limit 1;

  if p_sent and v_delivery_id is null then
    v_delivery_id := gen_random_uuid();
    insert into public.deliveries (
      id,
      legacy_id,
      order_id,
      district_id,
      shipping_method_id,
      delivery_at,
      delivery_time,
      ship_out_time,
      delivery_status,
      total_fee
    ) values (
      v_delivery_id,
      'web-delivery-' || v_delivery_id,
      p_order_id,
      v_order.delivery_district_id,
      v_order.shipping_method_id,
      v_order.delivery_at,
      v_order.delivery_time,
      v_order.ship_out_time,
      '未派車隊',
      v_order.shipping_fee
    );
  end if;

  return v_delivery_id;
end;
$$;

revoke all on function public.set_order_factory_status(uuid, boolean)
  from public, anon;
grant execute on function public.set_order_factory_status(uuid, boolean)
  to authenticated;

comment on function public.set_order_factory_status(uuid, boolean) is
  'Changes factory-send state and generates the first delivery only after an order is sent to the factory.';
